site_name: py_ocv
site_url: https://chaitu-ycr.github.io/py_proj_template/
site_description: Python 🐍 open source computer vision experiments
site_author: chaitu-ycr

repo_name: chaitu-ycr/py_ocv
repo_url: https://github.com/chaitu-ycr/py_ocv
edit_uri: blob/main/docs/


nav:
  - Documentation: index.md

theme:
  name: material
  features:
    - toc.integrate

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true